image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    develop: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
tasks: 
  - init: >-
      cd /workspace &&
      git clone https://github.com/caskdata/hydrator-plugins.git &&
      cd hydrator-plugins &&
      git submodule update --init --recursive --remote &&
      mvn clean package -DskipTests &&
      cd /workspace/cdap &&
      MAVEN_OPTS="-Xmx2048m " mvn package -pl cdap-standalone,cdap-app-templates/cdap-etl -am -amd -DskipTests -P templates,dist -Dadditional.artifacts.dir=/workspace/hydrator-plugins &&
      cd /workspace/cdap/cdap-standalone/target/sdk &&
      cd $(ls -d */|head -n 1) &&
      ./bin/cdap sandbox start
    command: >-
      cd /workspace/cdap/cdap-ui &&
      yarn &&
      yarn cdap-full-build &&
      cat <<< $(jq '.["dashboard.bind.port"]="11012"' server/config/development/cdap.json) > server/config/development/cdap.json &&
      yarn start
      name: Start UI server @ 11012
ports:
  - port: 11011
  - port: 11012
    onOpen: open-preview
  - port: 11015