image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    develop: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
tasks: 
  - before: MAVEN_OPTS="-Xmx2048m " mvn package -pl cdap-standalone,cdap-app-templates/cdap-etl -am -amd -DskipTests -P templates,dist -Dadditional.artifacts.dir=/workspace/hydrator-plugins && /workspace/cdap/cdap-standalone/target/sdk/cdap-sandbox-6.3.0-SNAPSHOT/bin sandbox start
    init: cd /workspace && git clone https://github.com/caskdata/hydrator-plugins.git && cd hydrator-plugins && git submodule update --init --recursive --remote && mvn clean package -DskipTests && cd /workspace/cdap
ports:
  - port: 11011
    onOpen: open-preview
  - port: 11015