# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CDAP UI Unit and Integration Tests

on:
  push:
    branches: [ develop, release/** ]
  pull_request:
    branches: [ develop, release/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.22.7]
        java-version: [8]

    # Cancel ongoing runs
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v2

    # installing dependency for node-canvas
    - name: Install Ubuntu debendency
      run: sudo apt-get install -y libgif-dev

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    # installing Java 8 to run the sandbox
    - name: Setup Java ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    - name: Download CDAP Sandbox and Start it
      run: |
        cd sandboxjs
        npm install -g yarn # Install Yarn globally
        yarn --frozen-lockfile # Install sandbox runner dependencies 
        yarn setup-gitpod $JAVA_HOME # Fetch and start sandbox
        sudo pkill -f node # Kill the sandbox UI

    - name: Install UI Dependencies
      run: |
        yarn --frozen-lockfile
        yarn run bower-root # Install Bower dependencies

    - name: Start CDAP-UI and run the tests
      run: |
        Xvfb :1 -screen 0 1024x768x24 & export DISPLAY=:1 # Set Display port
        yarn run cdap-full-build-more-memory # Build UI
        yarn start & > server.out
        yarn run test:unit
        yarn run test:integration
